language: python
python:
  - "2.7"
branches:
  only:
    master
cache:
  directories:
    - $HOME/.cache
    - $HOME/.ccache
before_install:
  - ccache -s
  - export PATH=/usr/lib/ccache:${PATH}
  - pip install --upgrade pip
# command to install dependencies
install:
  - "pip install -r requirements.txt"
# command to run tests
script: pytest