language: python
python:
  - "2.7"
# command to install dependencies
branches:
  only:
    master
before_install:
  - pip install --upgrade pip
  - pip install --upgrade numpy
install:
  - "pip install -r requirements.txt"
  - python -m nltk.downloader brown
  - "pip install -U scikit-learn"
# command to run tests
script:
  - python test.py