language: python
python:
  - "2.7"
# command to install dependencies
before_install:
  - pip install --upgrade pip
  - pip install --upgrade numpy
install:
  - "pip install -r requirements.txt"
  - "pip install -U scikit-learn"
# command to run tests
script: pytest
branches:
  only:
    master